/**
 * `npm run assets:fetch` — downloads the optional high-resolution imagery.
 *
 * Nothing here is required to run Demiurge. The procedural path is a supported
 * product configuration, not a fallback stub, and the default first load never
 * touches this directory. What these files buy is fidelity: real Blue Marble
 * albedo instead of noise, real Mars topography instead of a plausible
 * substitute.
 *
 * Three rules govern this script, and all three are about not being a bad
 * citizen of the public data commons:
 *
 * 1. Nothing downloaded is ever committed. `public/assets/**` is git-ignored.
 * 2. Every file records its licence, and `CREDITS.md` is regenerated from the
 *    manifest so attribution cannot drift from what was actually fetched.
 * 3. A 404 is a warning and a fall back to procedural generation, never a crash
 *    and never a silent retry storm against someone else's server.
 *
 * @module
 */

import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPOSITORY_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST_PATH = path.join(REPOSITORY_ROOT, 'data', 'assets.json');
const OUTPUT_ROOT = path.join(REPOSITORY_ROOT, 'public', 'assets');
const CREDITS_PATH = path.join(REPOSITORY_ROOT, 'CREDITS.md');

/** One downloadable asset, as described in `data/assets.json`. */
interface AssetEntry {
  /** Stable id, used as the cache key and in the credits table. */
  readonly id: string;
  /** Where it comes from. */
  readonly url: string;
  /** Where it lands, relative to `public/assets/`. */
  readonly target: string;
  /** SPDX identifier or a short licence name. */
  readonly license: string;
  /** Who to credit, as they ask to be credited. */
  readonly attribution: string;
  /** Human-readable source page, for the credits table. */
  readonly source: string;
  /** Expected SHA-256, when the upstream file is stable enough to pin. */
  readonly sha256?: string;
}

/** The manifest file's shape. */
interface AssetManifest {
  readonly assets: readonly AssetEntry[];
}

/** What happened to one asset. */
type FetchOutcome = 'downloaded' | 'skipped' | 'failed';

/**
 * Downloads one asset, verifying its checksum when the manifest pins one.
 *
 * @param entry - The asset to fetch.
 * @returns What happened, for the summary line.
 */
async function fetchAsset(entry: AssetEntry): Promise<FetchOutcome> {
  const destination = path.join(OUTPUT_ROOT, entry.target);

  try {
    const response = await fetch(entry.url);
    if (!response.ok) {
      console.warn(
        `  skip  ${entry.id}: ${String(response.status)} ${response.statusText}. ` +
          'Demiurge will generate this procedurally.',
      );
      return 'failed';
    }

    const bytes = Buffer.from(await response.arrayBuffer());

    if (entry.sha256 !== undefined) {
      const digest = createHash('sha256').update(bytes).digest('hex');
      if (digest !== entry.sha256) {
        console.warn(`  skip  ${entry.id}: checksum mismatch (got ${digest}). Not writing it.`);
        return 'failed';
      }
    }

    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, bytes);
    console.info(`  ok    ${entry.id} -> public/assets/${entry.target}`);
    return 'downloaded';
  } catch (error) {
    console.warn(`  skip  ${entry.id}: ${error instanceof Error ? error.message : String(error)}`);
    return 'failed';
  }
}

/**
 * Regenerates `CREDITS.md` from the manifest.
 *
 * @param manifest - Every asset the project knows how to fetch.
 */
async function writeCredits(manifest: AssetManifest): Promise<void> {
  const rows = manifest.assets
    .map(
      (entry) =>
        `| ${entry.id} | [${entry.source}](${entry.url}) | ${entry.attribution} | ${entry.license} |`,
    )
    .join('\n');

  const document = `<!-- Generated by \`npm run assets:fetch\`. Do not edit by hand. -->
# Credits

Demiurge runs with zero downloaded assets. Everything below is *optional*
imagery that \`npm run assets:fetch\` can pull in to raise fidelity; none of it
is committed to this repository.

| Asset | Source | Attribution | Licence |
| --- | --- | --- | --- |
${rows === '' ? '| _(none yet)_ | | | |' : rows}

## Software

Demiurge is MIT licensed. Its dependencies are checked against an allowlist by
\`npm run audit:licenses\`; see \`package.json\`.
`;

  await writeFile(CREDITS_PATH, document, 'utf8');
}

/**
 * Fetches everything in the manifest.
 */
async function main(): Promise<void> {
  const manifest = JSON.parse(await readFile(MANIFEST_PATH, 'utf8')) as AssetManifest;

  console.info(`\nFetching ${String(manifest.assets.length)} optional asset(s).\n`);

  const outcomes: FetchOutcome[] = [];
  for (const entry of manifest.assets) {
    // Sequential on purpose: these are large files from public science archives
    // and hammering them in parallel is rude.
    outcomes.push(await fetchAsset(entry));
  }

  await writeCredits(manifest);

  const downloaded = outcomes.filter((outcome) => outcome === 'downloaded').length;
  const failed = outcomes.filter((outcome) => outcome === 'failed').length;
  console.info(
    `\n${String(downloaded)} downloaded, ${String(failed)} unavailable (those bodies use procedural generation).`,
  );
  console.info('CREDITS.md regenerated.\n');
}

await main();
